### ISSUE TITLE
GitHub ActionsがPHP7.2でコケている。。

### ISSUE THREAD

**Issue by tekapo** [mt8/hello-tencho#5]
PHP7.2でこけて、PHP7.3、7.4までいってないようです。

https://github.com/mt8/hello-tencho/runs/4207639297?check_suite_focus=true#step:7:9
> Please run composer update.
と言ってますが、怪しいので7.2は無しでいいのではないかと。

7.2取り除いたら、7.3、7.4まで行きました!
https://github.com/tekapo/hello-tencho/actions/runs/1798507099

**Comment by mt8** [comment]
PHP7.2にさよならを告げます！

**Comment by mt8** [comment]
@tekapo PHP7.2にはさよならしました。 Thanks !
https://github.com/mt8/hello-tencho/pull/6
